;title=RAM Patcher
;version=1.0.0
;creator=Ch3ck3rM0n
;about='Patched Hekate und Atmosphere mit Support für 8GB RAM Modulen (MGCL/MGCR)'


[Ram Patcher ohne OC]
[Default - 4GB]
mirror_copy '/switch/.packages/RAM Patcher/Default/' /
; remove-ini-key '/bootloader/hekate_ipl.ini' 'CFW-EmuMMC' secmon exosphere.bin
delete /exosphere.bin

[MGCL/MGCR - 8GB]
mirror_copy '/switch/.packages/RAM Patcher/MGCL_8GB/' /
; set-ini-val '/bootloader/hekate_ipl.ini' 'CFW-EmuMMC' secmon exosphere.bin
move /exosphere_8GB.bin /exosphere.bin

;[Ram Patcher mit OC]
[MGCL/MGCR inkl. OC - 4GB]
mirror_copy '/switch/.packages/RAM Patcher/MGCL_4GB_OC/' /
; set-ini-val '/bootloader/hekate_ipl.ini' 'CFW-EmuMMC' secmon exosphere.bin
; set-ini-val '/bootloader/hekate_ipl.ini' 'KIP Patch hinzufügen' secmon exosphere.bin
delete /exosphere_8GB.bin

[MGCL/MGCR inkl. OC - 8GB]
mirror_copy '/switch/.packages/RAM Patcher/MGCL_8GB_OC/' /
; set-ini-val '/bootloader/hekate_ipl.ini' 'CFW-EmuMMC' secmon exosphere.bin
; set-ini-val '/bootloader/hekate_ipl.ini' 'KIP Patch hinzufügen' secmon exosphere.bin
move /exosphere_8GB.bin /exosphere.bin

[Complete - Neustart]
reboot boot CFW-EmuMMC

[Commands]
[Package Info]