;title=RAM Patcher
;version=1.10.2
;creator=Ch3ck3rM0n
;about='Patched Hekate + Atmosphere für OC-Support und 8GB RAM Modulen (MGCL/MGCR)'


[Ram Patcher ohne OC]
[Default - 4GB]
mirror_copy '/switch/.packages/RAM Patcher/Default/' /
delete /bootloader/ini/EmuMMC ohne Mods.ini
delete /bootloader/ini/emuMMC_8GB_nonOC.ini
delete /exosphere.bin

[MGCL/MGCR - 8GB]
mirror_copy '/switch/.packages/RAM Patcher/MGCL_8GB/' /
set-ini-val '/bootloader/hekate_ipl.ini' 'CFW-EmuMMC' secmon exosphere.bin
move /exosphere_8GB.bin /exosphere.bin
delete /bootloader/ini/emuMMC_8GB_nonOC.ini
delete /bootloader/ini/emuMMC_untouched.ini
delete /bootloader/ini/EmuMMC ohne Mods.ini

[Ram Patcher mit OC]
[Default inkl. OC - 4GB]
mirror_copy '/switch/.packages/RAM Patcher/MGCL_4GB_OC/' /
delete /bootloader/ini/emuMMC_8GB_nonOC.ini
delete /bootloader/ini/EmuMMC ohne Mods.ini
delete /exosphere_8GB.bin

[MGCL/MGCR inkl. OC - 8GB]
mirror_copy '/switch/.packages/RAM Patcher/MGCL_8GB_OC/' /
set-ini-val '/bootloader/hekate_ipl.ini' 'CFW-EmuMMC' secmon exosphere.bin
move /exosphere_8GB.bin /exosphere.bin
delete /bootloader/ini/emuMMC_untouched.ini
delete /bootloader/ini/EmuMMC ohne Mods.ini

[Commands]
[Complete - Neustart]
reboot boot CFW-EmuMMC

[Package Info]