;title=RAM Patcher
;version=1.10.1
;creator=Ch3ck3rM0n
;about='Patched Hekate + Atmosphere für OC-Support und 8GB RAM Modulen (MGCL/MGCR)'


[Ram Patcher ohne OC]
[Default - 4GB]
mirror_copy '/switch/.packages/RAM Patcher/Default/' /
delete /exosphere_8GB.bin
delete /exosphere_4GB.bin
delete /bootloader/ini/emuMMC_8GB_nonOC.ini

[MGCL/MGCR - 8GB]
mirror_copy '/switch/.packages/RAM Patcher/MGCL_8GB/' /
delete /bootloader/ini/emuMMC_8GB_nonOC.ini

[Ram Patcher mit OC]
[Default inkl. OC - 4GB]
mirror_copy '/switch/.packages/RAM Patcher/MGCL_4GB_OC/' /
delete /exosphere_8GB.bin
delete /exosphere_4GB.bin
delete /bootloader/ini/emuMMC_8GB_nonOC.ini

[MGCL/MGCR inkl. OC - 8GB]
mirror_copy '/switch/.packages/RAM Patcher/MGCL_8GB_OC/' /

[Commands]
[Complete - Neustart]
reboot boot CFW-EmuMMC

[Package Info]