[config]
autoboot=0
autoboot_list=0
bootwait=0
backlight=100
autohosoff=0
autonogc=0
updater2p=0
bootprotect=0
noticker=0

[CrDroid]
l4t=1
boot_prefixes=switchroot/android/
id=SWANDR
logopath=bootloader/bootlogo/bootlogo_android.bmp
icon=bootloader/res/android_hue.bmp
r2p_action=bootloader
ddr200_enable=1
usb3force=1
;dvfsb=1
;gpu_dvfsc=1
;oc=1
;max_cpu_freq=1966000
;max_gpu_freq=1228000
;ram_oc=2500000




;{NiklasCFW Ein Nintendo Switch CFW Pack}
;{Created by Woody2408 @ https://github.com/Woody-NX}
;{Niklas Discord Server @ https://discord.gg/KBmq9TGA}