[Commands]

[Hekate]
reboot HEKATE

[Hekate UMS]
reboot UMS

[Reboot CFW]
reboot boot CFW-EmuMMC

[Reboot OFW]
reboot boot OFW

[SHUTDOWN]
shutdown

#[*Payloads]
#[Tegra_Explorer]
#ini_file_source /bootloader/reboot/Tegra_Explorer.ini
#filter config
#reboot boot 'Tegra_Explorer'

#[Lockpick_RCM]
#ini_file_source /bootloader/reboot/Lockpick_RCM.ini
#filter config
#reboot ini 'Lockpick_RCM'

[*Weitere Optionen]
[CrDroid - nonOC]
ini_file_source /bootloader/ini/CrDroid_nonOC.ini
filter config
reboot ini 'CrDroid'

[Lakka - nonOC]
ini_file_source /bootloader/ini/Lakka_nonOC.ini
filter config
reboot ini 'Lakka'

[Ubuntu Noble - nonOC]
ini_file_source /bootloader/ini/Ubuntu_Noble_nonOC.ini
filter config
reboot ini 'Ubuntu_Noble'